# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/admin/CLionProjects/fhnw-syspr-work-01-Baselzockt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/admin/CLionProjects/fhnw-syspr-work-01-Baselzockt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/admin/CLionProjects/fhnw-syspr-work-01-Baselzockt/CMakeFiles /home/admin/CLionProjects/fhnw-syspr-work-01-Baselzockt//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/admin/CLionProjects/fhnw-syspr-work-01-Baselzockt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named size_of

# Build rule for target.
size_of: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 size_of
.PHONY : size_of

# fast build rule for target.
size_of/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/size_of.dir/build.make CMakeFiles/size_of.dir/build
.PHONY : size_of/fast

#=============================================================================
# Target rules for targets named args

# Build rule for target.
args: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 args
.PHONY : args

# fast build rule for target.
args/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/args.dir/build.make CMakeFiles/args.dir/build
.PHONY : args/fast

#=============================================================================
# Target rules for targets named tree

# Build rule for target.
tree: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree
.PHONY : tree

# fast build rule for target.
tree/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree.dir/build.make CMakeFiles/tree.dir/build
.PHONY : tree/fast

args.o: args.c.o
.PHONY : args.o

# target to build an object file
args.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/args.dir/build.make CMakeFiles/args.dir/args.c.o
.PHONY : args.c.o

args.i: args.c.i
.PHONY : args.i

# target to preprocess a source file
args.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/args.dir/build.make CMakeFiles/args.dir/args.c.i
.PHONY : args.c.i

args.s: args.c.s
.PHONY : args.s

# target to generate assembly for a file
args.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/args.dir/build.make CMakeFiles/args.dir/args.c.s
.PHONY : args.c.s

my_tree.o: my_tree.c.o
.PHONY : my_tree.o

# target to build an object file
my_tree.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree.dir/build.make CMakeFiles/tree.dir/my_tree.c.o
.PHONY : my_tree.c.o

my_tree.i: my_tree.c.i
.PHONY : my_tree.i

# target to preprocess a source file
my_tree.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree.dir/build.make CMakeFiles/tree.dir/my_tree.c.i
.PHONY : my_tree.c.i

my_tree.s: my_tree.c.s
.PHONY : my_tree.s

# target to generate assembly for a file
my_tree.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree.dir/build.make CMakeFiles/tree.dir/my_tree.c.s
.PHONY : my_tree.c.s

size_of.o: size_of.c.o
.PHONY : size_of.o

# target to build an object file
size_of.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/size_of.dir/build.make CMakeFiles/size_of.dir/size_of.c.o
.PHONY : size_of.c.o

size_of.i: size_of.c.i
.PHONY : size_of.i

# target to preprocess a source file
size_of.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/size_of.dir/build.make CMakeFiles/size_of.dir/size_of.c.i
.PHONY : size_of.c.i

size_of.s: size_of.c.s
.PHONY : size_of.s

# target to generate assembly for a file
size_of.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/size_of.dir/build.make CMakeFiles/size_of.dir/size_of.c.s
.PHONY : size_of.c.s

tree.o: tree.c.o
.PHONY : tree.o

# target to build an object file
tree.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree.dir/build.make CMakeFiles/tree.dir/tree.c.o
.PHONY : tree.c.o

tree.i: tree.c.i
.PHONY : tree.i

# target to preprocess a source file
tree.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree.dir/build.make CMakeFiles/tree.dir/tree.c.i
.PHONY : tree.c.i

tree.s: tree.c.s
.PHONY : tree.s

# target to generate assembly for a file
tree.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree.dir/build.make CMakeFiles/tree.dir/tree.c.s
.PHONY : tree.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... args"
	@echo "... size_of"
	@echo "... tree"
	@echo "... args.o"
	@echo "... args.i"
	@echo "... args.s"
	@echo "... my_tree.o"
	@echo "... my_tree.i"
	@echo "... my_tree.s"
	@echo "... size_of.o"
	@echo "... size_of.i"
	@echo "... size_of.s"
	@echo "... tree.o"
	@echo "... tree.i"
	@echo "... tree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

